In [2]:
import numpy as np

In [3]:
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3], [2,3,4]])

In [4]:
print('array1.shape : ', array1.shape) 
print('array2.shape : ', array2.shape)

array1.shape :  (3,)
array2.shape :  (2, 3)


In [5]:
print('array1.ndim : ', array1.ndim)
print('array2.ndim : ', array2.ndim)

array1.ndim :  1
array2.ndim :  2


In [6]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

list2 = [1, 2, 'test']
array2 = np.array(list2)  # 전부 문자열로 변환됨
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)  # 전부 실수형으로 변환됨
print(array3, array3.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
['1' '2' 'test'] <U11
[1. 2. 3.] float64


**ndarray 타입 변환**

* astype()을 이용하여 변환
* 대용량 데이터를 ndarray로 만들 때 메모리를 절약하기 위해 자주 사용.

In [11]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print('array_float : ', array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print('array_int1 : ', array_int1,  array_int1.dtype)

array_float1 = np.array([1.1, 2.2, 3.3])
array_int2 = array_float1.astype('int32')
print('array_int2 : ', array_int2, array_int2.dtype)

array_float :  [1. 2. 3.] float64
array_int1 :  [1 2 3] int32
array_int2 :  [1 2 3] int32


**ndarray의 axis축**

* ndarray의 shape는 행, 열, 높이 단위로 부여되는 것이 아니라, axis0, axis1, axis2와 같이 axis 단위로 부여
+ shape(2,4,5) -> axis0, axis1, axis2

In [13]:
array = np.array([[1,2,3], [2,3,4]])

print(array.sum())
print(array.sum(axis=0))
print(array.sum(axis=1))

15
[3 5 7]
[6 9]


**ndarray를 편리하게 생성하기 - arange, zeros, ones**

In [15]:
sequence_array = np.arange(10)
print("sequence_array : ", sequence_array)
print(sequence_array.dtype, sequence_array.shape)

sequence_array :  [0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [18]:
zero_array = np.zeros( (3,2), dtype='int32' )
print("zero_array : ", zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2)) # default dtype : float64
print("one_array : ", one_array)
print(one_array.dtype, one_array.shape)

zero_array :  [[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
one_array :  [[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


**ndarray의 shape를 변경하는 reshape()**

In [20]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [21]:
#변환할 수 없는 shape구조를 입력하면 오류 발생
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

reshape()에 -1 인자값을 부여하여 특정 차원으로 고정된 가변적인 ndarray의 형태 반환

In [26]:
array1 = np.arange(10)
print('array1 : ', array1)

#컬럼 axis 크기는 5에 고정하고 로우 axis 크기를 이에 맞춰 자동으로 변환(-> 2*5 형태로 변환)
array2 = array1.reshape(-1, 5)
print('array2.shape : ', array2.shape)
print('array2 : \n', array2)

# 로우 axis 크기는 5로 고정하고 컬럼 axis 크기는 이에 맞춰 자동으로 변환(-> 5*2 형태로 변환)
array3 = array1.reshape(5, -1)
print('array3.shape : ', array3.shape)
print('array3 : \n', array3)


array1 :  [0 1 2 3 4 5 6 7 8 9]
array2.shape :  (2, 5)
array2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3.shape :  (5, 2)
array3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [27]:
# reshape()는 (-1, 1), (-1,)와 같은 형태로 주로 사용됨
# 1차원 ndarray를 2차원으로 또는 2차원 ndarray를 1차원으로 변환 시 사용
array1 = np.arange(5)

# 1차원 ndarray를 2차원으로 변환하되, 컬럼axis크기는 반드시 1이어야 함
array2d_1 = array1.reshape(-1, 1)
print('array2d_1 shape : ', array2d_1.shape)
print('array2d_1:\n', array2d_1)

# 2차원 ndarray를 1차원으로 변환
array1d = array2d_1.reshape(-1,)
print('array1d shape : ', array1d.shape)
print('array1d:\n', array1d)

array2d_1 shape :  (5, 1)
array2d_1:
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape :  (5,)
array1d:
 [0 1 2 3 4]


In [28]:
# -1을 적용하여도 변환이 불가능한 형태로의 변환을 요구할 경우 오류 발생
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [29]:
# -1값은 반드시 1개의 인자만 입력해야 함
array1.reshape(-1, -1)

ValueError: can only specify one unknown dimension

---

## ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

<br>

**특정 위치의 단일값 추출**

In [36]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(1, 2) : ', array2d[1,2])
print('(2, 1) : ', array2d[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(1, 2) :  6
(2, 1) :  8


**슬라이싱(Slicing)**

In [37]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])


array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


**팬시 인덱싱(Fancy indexing)**

In [43]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ', array3.tolist()) #numpy.ndarray -> list

array4 = array2d[[0,2], 0:2]
print('array2d[[0,2], 0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,2], 0:2] =>  [[1, 2], [7, 8]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


**불린 인덱싱(Boolean indexing)**

In [44]:
array1d = np.arange(start=1, stop=10)
print(array1d)

[1 2 3 4 5 6 7 8 9]


In [46]:
var1 = array1d > 5
print('var1 : ', var1)
print(type(var1))

var1 :  [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [48]:
# [ ] 안에 array1d > 5 Boolean indexing 적용
print(array1d)
array3 = array1d[array1d > 5]
print('array1d >5  boolean indexing 결과 값 : ', array3)

[1 2 3 4 5 6 7 8 9]
array1d >5  boolean indexing 결과 값 :  [6 7 8 9]


In [49]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('boolean index로 필터링 결과 : ', array3)

boolean index로 필터링 결과 :  [6 7 8 9]


In [50]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 : ', array4)

일반 인덱스로 필터링 결과 :  [6 7 8 9]


In [51]:
array1d = np.arange(start=1, stop=10)
target = []

for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)
print('array_selected : ', array_selected)

array_selected :  [6 7 8 9]


In [53]:
print(array1d[array1d > 5])

[6 7 8 9]
